// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    MyAlbum: typeof import('./src/components/MyMian/component/MyAlbum/index.vue')['default']
    MyBorderBox: typeof import('./src/components/component/MyBorderBox/index.vue')['default']
    MyCart: typeof import('./src/components/component/MyCart/index.vue')['default']
    MyDetail: typeof import('./src/components/MyMian/component/MyInforCard/MyDetail/index.vue')['default']
    MyFireworks: typeof import('./src/components/component/MyFireworks/index.vue')['default']
    MyHome: typeof import('./src/components/MyMian/component/MyHome/index.vue')['default']
    MyInforCard: typeof import('./src/components/MyMian/component/MyInforCard/index.vue')['default']
    MyLnformation: typeof import('./src/components/MyMian/component/MyLnformation/index.vue')['default']
    MyMeteor: typeof import('./src/components/component/MyMeteor/index.vue')['default']
    MyMian: typeof import('./src/components/MyMian/index.vue')['default']
    MyRain: typeof import('./src/components/component/MyRain/index.vue')['default']
    MyStar: typeof import('./src/components/component/MyStar/index.vue')['default']
    MyStudent: typeof import('./src/components/MyMian/component/MyStudent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
