// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    MyAlbum: typeof import('./src/components/MyMian/component/MyAlbum/index.vue')['default']
    MyCard: typeof import('./src/components/myCard/index.vue')['default']
    MyCart: typeof import('./src/components/component/MyCart/index.vue')['default']
    MyHome: typeof import('./src/components/MyMian/component/MyHome/index.vue')['default']
    MyInforCard: typeof import('./src/components/MyMian/component/MyInforCard/index.vue')['default']
    MyLnformation: typeof import('./src/components/MyMian/component/MyLnformation/index.vue')['default']
    MyMeteor: typeof import('./src/components/component/MyMeteor/index.vue')['default']
    MyMian: typeof import('./src/components/MyMian/index.vue')['default']
    MyNav: typeof import('./src/components/myNav.vue')['default']
    MyRain: typeof import('./src/components/component/MyRain/index.vue')['default']
    MySnow: typeof import('./src/components/mySnow.vue')['default']
    MyStar: typeof import('./src/components/component/MyStar/index.vue')['default']
    MyStudent: typeof import('./src/components/MyMian/component/MyStudent/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
